#ifndef RTW_HEADER_BESS_PCS_Ref_acc_types_h_
#define RTW_HEADER_BESS_PCS_Ref_acc_types_h_
typedef struct P_RMS_BESS_PCS_Ref_T_ P_RMS_BESS_PCS_Ref_T ; typedef struct
P_TrueRMS_BESS_PCS_Ref_T_ P_TrueRMS_BESS_PCS_Ref_T ; typedef struct
P_CLARK_BESS_PCS_Ref_T_ P_CLARK_BESS_PCS_Ref_T ; typedef struct
P_Regulator_BESS_PCS_Ref_T_ P_Regulator_BESS_PCS_Ref_T ; typedef struct
P_Subsystempi2delay_BESS_PCS_Ref_T_ P_Subsystempi2delay_BESS_PCS_Ref_T ;
typedef struct P_Subsystem1_BESS_PCS_Ref_T_ P_Subsystem1_BESS_PCS_Ref_T ;
typedef struct P_DCVoltageControlOverride_BESS_PCS_Ref_T_
P_DCVoltageControlOverride_BESS_PCS_Ref_T ; typedef struct
P_Int_regulatortype1_BESS_PCS_Ref_T_ P_Int_regulatortype1_BESS_PCS_Ref_T ;
typedef struct P_DC_Voltage_Control_BESS_PCS_Ref_T_
P_DC_Voltage_Control_BESS_PCS_Ref_T ; typedef struct
P_Subsystempi2delay_BESS_PCS_Ref_n_T_ P_Subsystempi2delay_BESS_PCS_Ref_n_T ;
typedef struct P_Subsystem1_BESS_PCS_Ref_j_T_ P_Subsystem1_BESS_PCS_Ref_j_T ;
typedef struct P_Fullbridge1ph_BESS_PCS_Ref_T_ P_Fullbridge1ph_BESS_PCS_Ref_T
; typedef struct P_Halfbridge1phand3phbridge_BESS_PCS_Ref_T_
P_Halfbridge1phand3phbridge_BESS_PCS_Ref_T ; typedef struct P_BESS_PCS_Ref_T_
P_BESS_PCS_Ref_T ;
#endif
